#pragma once

#define WINSYS_DEVICE 0x8088
#define KWINSYS_DEVNAME L"\\\\.\\KWinSys"
#define KWINSYS_VERSION 0x100

#define IOCTL_WINSYS_GET_VERSION				CTL_CODE(WINSYS_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINSYS_OPEN_OBJECT_BY_ADDRESS		CTL_CODE(WINSYS_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINSYS_DUP_HANDLE					CTL_CODE(WINSYS_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINSYS_OPEN_OBJECT_BY_NAME		CTL_CODE(WINSYS_DEVICE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINSYS_OPEN_PROCESS				CTL_CODE(WINSYS_DEVICE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINSYS_OPEN_THREAD				CTL_CODE(WINSYS_DEVICE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINSYS_GET_OBJECT_ADDRESS			CTL_CODE(WINSYS_DEVICE, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

struct OpenObjectByAddressData {
	void* Address;
	ACCESS_MASK Access;
};

struct OpenObjectByNameData {
	ACCESS_MASK Access;
	ULONG TypeIndex;
	WCHAR Name[1];
};

struct DupHandleData {
	ULONG SourceHandle;
	ULONG SourcePid;
	ACCESS_MASK AccessMask;
	ULONG Flags;
};

struct OpenProcessThreadData {
	ULONG Id;
	ACCESS_MASK AccessMask;
};

